receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
        
processors:
  batch:
    timeout: 1s
  # resource:
  #   attributes:
  #     - key: test.key
  #       value: "test-value"
  #       action: insert
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, service.namespace
      - action: insert
        key: loki.format
        value: json

exporters:
  logging:
    loglevel: info

  prometheus:
    endpoint: 0.0.0.0:8889

  
  # jaeger:
  #   endpoint: jaeger:14250
  #   tls:
  #     insecure: true
  ## Create an exporter to Jaeger using the standard `otlp` export format
  #https://stackoverflow.com/questions/77475771/error-when-running-otel-collector-with-jaeger-in-docker-containers
  otlp:
    endpoint: jaeger:14250
    tls:
      insecure: true

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

  #https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15653
  #https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21473 Label Breaking Change
  # ย้ายไปใน Resource Section แทน https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    #format: json
    #labels:
    #  resource:
    #   service.name: "service_name"
    #    service.instance.id: "service_instance_id"
        

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [batch, resource]
      processors: [batch]
      #exporters: [logging, jaeger, zipkin]
      exporters: [logging, otlp, zipkin]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki]

